### ISSUE TITLE
need help for config and run

### ISSUE THREAD

**Issue by littleben** [JokerQyou/bot#36]
config.json file like this:

>  "webhook": true,
>     "fetch_interval": 1,
>     "use_nginx": true,
>     "ssl_cert": "/path/to/cert/file",
>     "ssl_key": "/path/to/key/file",
>     "debug": false,
>     "token": "88888:3169xxxxxxxxxxb3b1",
>     "server": "test.com/bot",
>     "port": 9003,

run  python -u worker.py and get error

```
pi@raspberrypi:~/tlbot $ python -u worker.py
Traceback (most recent call last):
  File "worker.py", line 31, in <module>
    main()
  File "worker.py", line 28, in main
    worker.work()
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 404, in work
    self.register_birth()
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 235, in register_birth
    if self.connection.exists(self.key) and \
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 855, in exists
    return self.execute_command('EXISTS', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```

**Comment by JokerQyou** [comment]
Umm, there is an external requirement not written in README: you should have Redis running because it uses `rq` as task queue.

**Comment by littleben** [comment]
Thanks, it works :)
